---
- name: "Patch Enterprise Linux"
  block:
    # For testing whether or not we need a reboot or service restart we need yum-utils
    #   installed to utilize the needs-restarting utility
    - name: "Ensure yum-utils is installed"
      yum:
        name: "yum-utils"
        state: "present"
      register: "patch_utils_installed"
      retries: "3"
      until: "patch_utils_installed is succeeded"

    - name: "Update packages"
      yum:
        name: "{{ patch_pkgs | default('*') }}"
        state: "latest"
        update_cache: "yes"
      register: "patch_yum_results"
      retries: "3"
      until: "patch_yum_results is succeeded"

    - name: "Check if services need restarting"
      command: 'needs-restarting -s'
      changed_when: "needs_service_restart.stdout_lines | length > 0"
      register: "needs_service_restart"
      notify:
        - "Restart required services"
      when: 'not patch_never_restart_svc'

    - name: "Check if reboot is required"
      command:  'needs-restarting -r'
      changed_when: "needs_reboot.rc == 1"
      failed_when: "needs_reboot.rc > 1"
      register: "needs_reboot"
      notify:
        - "Reboot after patching"
      when: 'not patch_never_reboot'

    - name: "Output collected yum update output"
      debug:
         var: "patch_yum_results.results"
      when: "patch_display_patch_output"
  when:
    - 'ansible_os_family == "RedHat"'
    - 'ansible_distribution_major_version == "7"'
  become: True
