---
- name: "Restart required services"
  service:
    name: "{{ item }}"
    state: "restarted"
  when:
    - 'needs_service_restart.stdout_lines | length > 0'
    - 'needs_reboot.rc != 1'
    - 'not patch_never_restart_svc'
  with_items: "{{ needs_service_restart.stdout_lines }}"

- name: "Reboot after patching"
  reboot:
    msg: "{{ patch_reboot_message | default('Rebooting due to patching.') }}"
  when:
    - 'needs_reboot.rc == 1'
    - 'not patch_never_reboot'
